### ISSUE TITLE
use Instance role access instead of access keys

### ISSUE THREAD

**Issue by himadrisingh** [zhichen/elasticsearch-repository-oss#16]
If access_key_id is not specified it should fallback to instance roles

```
Caused by: org.elasticsearch.repositories.RepositoryException: [nightly] Setting [access_key_id] is empty for repository
at org.elasticsearch.repository.oss.OssRepository.getSetting(OssRepository.java:79) ~[?:?]
at org.elasticsearch.aliyun.oss.service.OssServiceImpl.createClient(OssServiceImpl.java:34) ~[?:?]
at org.elasticsearch.aliyun.oss.service.OssServiceImpl.<init>(OssServiceImpl.java:24) ~[?:?]
at org.elasticsearch.plugin.repository.oss.OssRepositoryPlugin.createStorageService(OssRepositoryPlugin.java:41) ~[?:?]
at org.elasticsearch.plugin.repository.oss.OssRepositoryPlugin.lambda$getRepositories$1(OssRepositoryPlugin.java:48) ~[?:?]
```

**Comment by himadrisingh** [comment]
this was from 5.3, latest ones have support for sts roles.
