### ISSUE TITLE
es6.4.3 错误

### ISSUE THREAD

**Issue by StandNorthStar** [zhichen/elasticsearch-repository-oss#7]
由于我当前使用的ES版本是 6.4.3 ，所以下载oss插件版本是6.3.2。 
按照要求修改：
version= 6.4.3
elasticsearch.version=6.4.3
ES服务启动正常

curl -XPUT 'http://localhost:9200/_snapshot/test' -H 'Content-Type: application/json' -d '
{
"type": "oss",
"settings":
    {
   "access_key_id": "xxxxxx",
   "secret_access_key": "xxxxxx",
   "bucket": "backup",
   "endpoint": "http://oss-cn-beijing.aliyuncs.com"
} 
}
' | jq
执行上面命令时ES服务直接挂掉，请问是什么原因？

错误：
[2019-08-07T11:32:54,409][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [elasticsearch-6.4.3] fatal error in thread [elasticsearch[elasticsearch-6.4.3][snapshot][T#1]], exiting
java.lang.AbstractMethodError: Method org/elasticsearch/aliyun/oss/blobstore/OssBlobContainer.writeBlob(Ljava/lang/String;Ljava/io/InputStream;JZ)V is abstract
	at org.elasticsearch.aliyun.oss.blobstore.OssBlobContainer.writeBlob(OssBlobContainer.java) ~[?:?]
	at org.elasticsearch.common.blobstore.BlobContainer.writeBlobAtomic(BlobContainer.java:102) ~[elasticsearch-6.4.3.jar:6.4.3]
	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.startVerification(BlobStoreRepository.java:639) ~[elasticsearch-6.4.3.jar:6.4.3]
	at org.elasticsearch.repositories.RepositoriesService.lambda$verifyRepository$2(RepositoriesService.java:218) ~[elasticsearch-6.4.3.jar:6.4.3]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:624) ~[elasticsearch-6.4.3.jar:6.4.3]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

**Comment by StandNorthStar** [comment]
我替换ES版本测试后，
[root@elasticsearch-6 elasticsearch]# 
[root@elasticsearch-6 elasticsearch]# curl -XPUT 'http://localhost:9200/_snapshot/test' -H 'Content-Type: application/json' -d '
> {
> "type": "oss",
> "settings":
>     {
>    "access_key_id": "xxxxx",
>    "secret_access_key": "xxxxxxxxxx",
>    "bucket": "xxxx-xxxxx",
>    "endpoint": "http://oss-xxxxxxxx.aliyuncs.com",
>    "compress": true
> } 
> }
> ' | jq
{
  "acknowledged": true
}
查看阿里云桶上并无上传数据，查看ES日志 下面错误。
[2019-08-07T14:53:51,117][INFO ][c.a.oss ] [Server]Unable to execute HTTP request: The specified key does not exist.
[ErrorCode]: NoSuchKey
[RequestId]: xxxxxxxxxxxxxxxxxx
[HostId]:xxxxxxxxxx.xxxxxxxx.aliyuncs.com
[ResponseError]:
<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>NoSuchKey</Code>
  <Message>The specified key does not exist.</Message>
  <RequestId>xxxxxxxxxxxxxxx</RequestId>
  <HostId>xxxxx..oss-xxxxxxx.aliyuncs.com</HostId>
  <Key>xxxxxxxxxxxx/dataxxxxxxxxxxxxxxxx.dat</Key>
</Error>

**Comment by oldthreefeng** [comment]
相同错误。。
6.8.6 版本

**Comment by luyang-yanglu** [comment]
curl -X PUT "localhost:9200/_snapshot/oss_snapshot?pretty" -H 'Content-Type: application/json' -d'
{
  "type": "oss",
  "settings": {
    "bucket": "dbmanager-oss-snapshot",
    "endpoint": "oss-cn*******************s.com",
    "access_key_id": "U*********",
    "secret_access_key": "*************",
    "compress": true
  }
}
'
6.4.0版本也踩坑了；执行上面命令时ES服务直接挂掉，请问是什么原因？
[2023-04-26T16:33:40,974][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [] fatal error in thread [elasticsearch[pQrDJaZ][snapshot][T#1]], exiting
java.lang.AbstractMethodError: Method org/elasticsearch/aliyun/oss/blobstore/OssBlobContainer.writeBlob(Ljava/lang/String;Ljava/io/InputStream;JZ)V is abstract
        at org.elasticsearch.aliyun.oss.blobstore.OssBlobContainer.writeBlob(OssBlobContainer.java) ~[?:?]
        at org.elasticsearch.common.blobstore.BlobContainer.writeBlobAtomic(BlobContainer.java:102) ~[elasticsearch-6.4.0.jar:6.4.0]
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository.startVerification(BlobStoreRepository.java:639) ~[elasticsearch-6.4.0.jar:6.4.0]
        at org.elasticsearch.repositories.RepositoriesService.lambda$verifyRepository$2(RepositoriesService.java:218) ~[elasticsearch-6.4.0.jar:6.4.0]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:624) ~[elasticsearch-6.4.0.jar:6.4.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_251]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_251]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]

**Comment by oldthreefeng** [comment]
> curl -X PUT "localhost:9200/_snapshot/oss_snapshot?pretty" -H 'Content-Type: application/json' -d'
> {
>   "type": "oss",
>   "settings": {
>     "bucket": "dbmanager-oss-snapshot",
>     "endpoint": "oss-cn*******************s.com",
>     "access_key_id": "U*********",
>     "secret_access_key": "*************",
>     "compress": true
>   }
> }
> '
> 6.4.0版本也踩坑了；执行上面命令时ES服务直接挂掉，请问是什么原因？
> [2023-04-26T16:33:40,974][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [] fatal error in thread [elasticsearch[pQrDJaZ][snapshot][T#1]], exiting
> java.lang.AbstractMethodError: Method org/elasticsearch/aliyun/oss/blobstore/OssBlobContainer.writeBlob(Ljava/lang/String;Ljava/io/InputStream;JZ)V is abstract
>         at org.elasticsearch.aliyun.oss.blobstore.OssBlobContainer.writeBlob(OssBlobContainer.java) ~[?:?]
>         at org.elasticsearch.common.blobstore.BlobContainer.writeBlobAtomic(BlobContainer.java:102) ~[elasticsearch-6.4.0.jar:6.4.0]
>         at org.elasticsearch.repositories.blobstore.BlobStoreRepository.startVerification(BlobStoreRepository.java:639) ~[elasticsearch-6.4.0.jar:6.4.0]
>         at org.elasticsearch.repositories.RepositoriesService.lambda$verifyRepository$2(RepositoriesService.java:218) ~[elasticsearch-6.4.0.jar:6.4.0]
>         at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:624) ~[elasticsearch-6.4.0.jar:6.4.0]
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_251]
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_251]
>         at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
> 

兄弟别用插件了，直接把oss当做sc ， 以目录的形式挂载，这样不用考虑版本问题.
