### ISSUE TITLE
支持 7.3.0

### ISSUE THREAD

**Issue by ZhaoBaymax** [zhichen/elasticsearch-repository-oss#8]
现在可以支持7.3.0吗 修改版本号好像不起作用

**Comment by anjia0532** [comment]
https://github.com/anjia0532/elasticsearch-repository-oss/releases/tag/v7.3.2

**Comment by liuyihan** [comment]
@anjia0532 创建repository失败，org.elasticsearch.common.blobstore.BlobStoreException: Failed to check if blob [master.dat] exists

**Comment by Nan-Sen1024** [comment]
[=================================================] 100%   
Exception in thread "main" java.lang.IllegalArgumentException: Plugin [elasticsearch-repository-oss] was built for Elasticsearch version 7.3.2 but version 7.3.0 is running
	at org.elasticsearch.plugins.PluginsService.verifyCompatibility(PluginsService.java:346)
	at org.elasticsearch.plugins.InstallPluginCommand.loadPluginInfo(InstallPluginCommand.java:727)
	at org.elasticsearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:802)
	at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:785)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:231)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:216)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:77)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)
